# Generated by Django 2.2 on 2021-04-09 18:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(blank=True, max_length=2000, null=True)),
                ('file_address', models.FileField(blank=True, null=True, upload_to='files/message_file')),
                ('message_type', models.CharField(choices=[('t', 'text'), ('i', 'image'), ('v', 'video'), ('a', 'audio')], default='t', max_length=1)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.Channel', verbose_name='')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.UserProfile', verbose_name='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
