# Generated by Django 2.2 on 2021-04-12 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelmessage',
            old_name='file_address',
            new_name='message_file',
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
    ]
