# Generated by Django 2.2 on 2021-04-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='invite_link',
            field=models.CharField(max_length=32),
        ),
    ]
