# Generated by Django 2.2 on 2021-04-25 12:51

import channel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='files/channel_avatar', validators=[channel.models.validate_avatar_extension]),
        ),
    ]
