# Generated by Django 2.2 on 2021-04-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_baseuser_user_type'),
        ('channel', '0003_auto_20210406_1301'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('channel', 'user')},
        ),
    ]
