# Generated by Django 2.2 on 2021-03-15 18:07

import User.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[User.models.validate_phone_number])),
                ('private_profile', models.BooleanField(default=False)),
                ('avatar', models.FileField(blank=True, null=True, upload_to='files/user_avatar', validators=[User.models.validate_avatar_extension])),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.UserProfile')),
                ('accepted', models.BooleanField(default=False)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='lawyers/certificate')),
                ('my_secretaries', models.ManyToManyField(related_name='my_consultants', to='User.UserProfile')),
            ],
            options={
                'abstract': False,
            },
            bases=('User.userprofile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
