# Generated by Django 2.2 on 2021-04-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='private_profile',
            field=models.BooleanField(default=False),
        ),
    ]
