# Generated by Django 2.2 on 2021-04-19 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.CharField(blank=True, max_length=2000, null=True)),
                ('answer_text', models.CharField(blank=True, max_length=2000, null=True)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('answer_date', models.DateTimeField(null=True)),
                ('accept', models.BooleanField(default=False)),
                ('request_type', models.CharField(choices=[('join_channel', 'join_channel'), ('secretary', 'secretary')], default='join_channel', max_length=32)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='User.ConsultantProfile', verbose_name='Applicant')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Target User')),
            ],
        ),
    ]
