# Generated by Django 2.2 on 2021-04-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='user_type',
            field=models.CharField(choices=[('Lawyer', 'Lawyer'), ('normal_user', 'normal_user'), ('medical', 'medical'), ('Entrance_Exam', 'Entrance_Exam'), ('Psychology', 'Psychology'), ('Educationalـimmigration', 'Educationalـimmigration'), ('Academicـadvice', 'Academicـadvice')], default='normal_user', max_length=32),
        ),
    ]
