# Generated by Django 2.2 on 2021-04-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_consultantprofile_private_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='user_type',
            field=models.CharField(default='normal_user', max_length=32),
        ),
    ]
